site_name: Codebase Examiner
site_description: A tool to examine Python codebases and generate documentation
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
  palette:
    primary: custom
    accent: custom
  custom_dir: docs/overrides
  logo: assets/mojility_favicon.png
  favicon: assets/mojility_favicon.png
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [ "src" ]
          import:
            - https://docs.python.org/3/objects.inv
            - https://docs.pydantic.dev/latest/objects.inv
          options:
            docstring_style: "google"
            heading_level: 2
            show_source: true
            show_category_heading: true
            show_root_heading: true
            show_if_no_docstring: false
            extensions:
              - griffe_fieldz
      enable_inventory: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Extending: extending.md
  - API Reference: api-reference.md

repo_name: codebase-examiner
repo_url: https://github.com/svetzal/codebase-examiner
